[workspace]
resolver = "2"
members = [
    "sophgo-hal",
    "sophgo-rom-rt",
    "sophgo-rom-rt/macros",
    "sophgo-rom-tool",
    "examples/hello-world",
]

[workspace.package]
edition = "2021"
license = "MulanPSL-2.0 OR MIT"
repository = "https://github.com/rustsbi/sophgo-hal"
